### Get backup data
GET http://localhost:5200/api/backup
Content-Type: application/json
X-Api-Key: apikey

### Restore data
POST http://localhost:5200/api/backup/restore
Content-Type: application/json
X-Api-Key: apikey

{
    "weightRecords": [
        {
            "weightId": "955c82e8-124a-427b-9160-358db7e51e41",
            "date": "2025-04-18T07:23:29.049Z",
            "weight": 12
        },
        {
            "weightId": "5bf0a60a-58d9-4136-8b4c-85a82e34fb02",
            "date": "2025-04-18T07:24:00.591Z",
            "weight": 43
        }
    ]
}
