### Get backup data (all users + all weights)
GET http://localhost:5200/api/backup
Content-Type: application/json
X-Api-Key: apikey

### Restore data (users + weights)
POST http://localhost:5200/api/backup/restore
Content-Type: application/json
X-Api-Key: apikey

{
  "users": [
    { "userId": "ApiUser", "heightInCm": 150 }
  ],
  "weightRecords": [
    {
      "weightId": "955c82e8-124a-427b-9160-358db7e51e41",
      "userId": "ApiUser",
      "date": "2025-04-18T07:23:29.049Z",
      "weight": 12,
      "deleted": true
    },
    {
      "weightId": "5bf0a60a-58d9-4136-8b4c-85a82e34fb02",
      "userId": "ApiUser",
      "date": "2025-04-18T07:24:00.591Z",
      "weight": 43,
      "deleted": false
    }
  ]
}

### Restore empty (wipes everything)
POST http://localhost:5200/api/backup/restore
Content-Type: application/json
X-Api-Key: apikey

{
  "users": [],
  "weightRecords": []
}
