
@baseUrl = http://localhost:5200/api

### Get backup data
GET {{baseUrl}}/backup
X-Api-Key: apikey

### create entry
# @name createWeight
POST {{baseUrl}}/weight
Content-Type: application/json
X-Api-Key: apikey

{           
    "date": "2025-04-18T07:23:29.049Z",
    "weight": 12
}


### get created entry

@locationHeader = {{createWeight.response.headers.Location}}

### {{locationHeader}}

GET {{locationHeader}}
X-Api-Key: apikey

### delete created entry

DELETE {{locationHeader}}
X-Api-Key: apikey
