
@baseUrl = http://localhost:5200/api

### create entry
# @name createWeight
POST {{baseUrl}}/weight
Content-Type: application/json
X-Api-Key: apikey

{
    "date": "2025-04-18T07:23:29.049Z",
    "weight": 12,
    "comment": "after a big lunch"
}


### get created entry

@locationHeader = {{createWeight.response.headers.Location}}

### {{locationHeader}}

GET {{locationHeader}}
X-Api-Key: apikey


### update the comment on the created entry

PUT {{locationHeader}}
Content-Type: application/json
X-Api-Key: apikey

{
    "comment": "added this note later"
}

### get all entries for user

GET {{baseUrl}}/weights
X-Api-Key: apikey



### delete created entry

DELETE {{locationHeader}}
X-Api-Key: apikey
